### ISSUE TITLE
when i try to compile the program, i get an error that tells me that NAudio is missing

### ISSUE THREAD

**Issue by ghost** [nzgamer41/nub2wav#1]
any help?

![image](https://user-images.githubusercontent.com/48196796/107489249-47259a80-6bed-11eb-9f4f-6f689067f166.png)

**Comment by nzgamer41** [comment]
you need to restore the packages from nuget, I don't know if it's designed to work out of the box with .NET 5.0 which you seem to be running which may also cause issues.
